"""make slug not null

Revision ID: 01d613222476
Revises: 757d22bc8ecc
Create Date: 2025-05-06 16:53:51.562692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '01d613222476'
down_revision: Union[str, None] = '757d22bc8ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finetuning_group', 'slug',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finetuning_group', 'slug',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
