"""add ft job

Revision ID: 02c2268d81b2
Revises: 13341b03ae43
Create Date: 2025-06-18 12:26:55.772989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '02c2268d81b2'
down_revision: Union[str, None] = '13341b03ae43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_group',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('llm_group_membership',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('llm_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['llm_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('llm_group_membership_ix_group_id_llm_id_uniq', 'llm_group_membership', ['group_id', 'llm_id'], unique=True)
    op.add_column('finetuning_job', sa.Column('source_llm_group_id', sa.Uuid(), nullable=True))
    op.alter_column('finetuning_job', 'source_llm_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'finetuning_job', 'llm_group', ['source_llm_group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finetuning_job', type_='foreignkey')
    op.alter_column('finetuning_job', 'source_llm_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('finetuning_job', 'source_llm_group_id')
    op.drop_index('llm_group_membership_ix_group_id_llm_id_uniq', table_name='llm_group_membership')
    op.drop_table('llm_group_membership')
    op.drop_table('llm_group')
    # ### end Alembic commands ###
