"""add response fields

Revision ID: 03e8e374a89d
Revises: abf722fad99d
Create Date: 2025-04-12 22:10:34.584764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03e8e374a89d'
down_revision: Union[str, None] = 'abf722fad99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('sample_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('response', sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'raw_response')
    op.drop_column('response', 'sample_cfg')
    # ### end Alembic commands ###
