"""make external id unique

Revision ID: 0f24a7f21b23
Revises: 188295a6853d
Create Date: 2025-04-10 10:27:17.124658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f24a7f21b23"
down_revision: Union[str, None] = "188295a6853d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "llm", ["external_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "llm", type_="unique")
    # ### end Alembic commands ###
