"""add canceleld status

Revision ID: 13341b03ae43
Revises: 8b49d600488e
Create Date: 2025-06-16 20:35:48.428277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '13341b03ae43'
down_revision: Union[str, None] = '8b49d600488e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation_run', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('new', 'pending', 'complete', 'failed', 'cancelled', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation_run', 'status',
               existing_type=sa.Enum('new', 'pending', 'complete', 'failed', 'cancelled', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
