"""add judgment models

Revision ID: 14b0ad8e386d
Revises: f871d8b476de
Create Date: 2025-04-11 17:50:53.278084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b0ad8e386d'
down_revision: Union[str, None] = 'f871d8b476de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_judgment',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('judge_llm_id', sa.Uuid(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_llm_id'], ['llm.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_row_judgment',
    sa.Column('judgement_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_row_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_row_id'], ['dataset_row.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judgement_id'], ['dataset_judgment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dataset_row_judgment_judgment_id_dataset_row_id_unique', 'dataset_row_judgment', ['judgement_id', 'dataset_row_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dataset_row_judgment_judgment_id_dataset_row_id_unique', table_name='dataset_row_judgment')
    op.drop_table('dataset_row_judgment')
    op.drop_table('dataset_judgment')
    # ### end Alembic commands ###
