"""add external ids

Revision ID: 17369098ecb2
Revises: 8122fa7c431c
Create Date: 2025-04-09 23:17:31.859932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17369098ecb2"
down_revision: Union[str, None] = "8122fa7c431c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm", sa.Column("external_id", sa.String(), nullable=False))
    op.add_column("llm", sa.Column("external_org_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm", "external_org_id")
    op.drop_column("llm", "external_id")
    # ### end Alembic commands ###
