"""rename column

Revision ID: 1c3d23b1bb1c
Revises: fb9da2de82c0
Create Date: 2025-05-03 14:38:48.151413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '1c3d23b1bb1c'
down_revision: Union[str, None] = 'fb9da2de82c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('response_id', sa.Uuid(), nullable=False))
    op.add_column('embedding', sa.Column('vector', truesight.db.models.Vector(1536), nullable=False))
    op.drop_constraint('embedding_question_id_key', 'embedding', type_='unique')
    op.create_unique_constraint(None, 'embedding', ['response_id'])
    op.drop_constraint('embedding_question_id_fkey', 'embedding', type_='foreignkey')
    op.create_foreign_key(None, 'embedding', 'response', ['response_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('embedding', 'embedding')
    op.drop_column('embedding', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('embedding', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'embedding', type_='foreignkey')
    op.create_foreign_key('embedding_question_id_fkey', 'embedding', 'response', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'embedding', type_='unique')
    op.create_unique_constraint('embedding_question_id_key', 'embedding', ['question_id'])
    op.drop_column('embedding', 'vector')
    op.drop_column('embedding', 'response_id')
    # ### end Alembic commands ###
