"""add nickname

Revision ID: 20017e22fc96
Revises: 13b979121c45
Create Date: 2025-06-09 11:47:58.640668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '20017e22fc96'
down_revision: Union[str, None] = '13b979121c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('nickname', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm', 'nickname')
    # ### end Alembic commands ###
