"""add more field

Revision ID: 202ea44a668d
Revises: 3f475f817930
Create Date: 2025-06-10 14:01:12.399447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '202ea44a668d'
down_revision: Union[str, None] = '3f475f817930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_finetuning_job_link',
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('finetuning_job_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finetuning_job_id'], ['finetuning_job.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('experiment_evaluation_link_finetuning_job_id_llm_id_uniq', 'experiment_finetuning_job_link', ['experiment_id', 'finetuning_job_id'], unique=True)
    op.drop_index(op.f('experiment_evaluation_link_llm_id_evaluation_id_uniq'), table_name='experiment_llm_link')
    op.create_index('experiment_evaluation_link_experiment_id_llm_id_uniq', 'experiment_llm_link', ['experiment_id', 'llm_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('experiment_evaluation_link_experiment_id_llm_id_uniq', table_name='experiment_llm_link')
    op.create_index(op.f('experiment_evaluation_link_llm_id_evaluation_id_uniq'), 'experiment_llm_link', ['experiment_id', 'llm_id'], unique=True)
    op.drop_index('experiment_evaluation_link_finetuning_job_id_llm_id_uniq', table_name='experiment_finetuning_job_link')
    op.drop_table('experiment_finetuning_job_link')
    # ### end Alembic commands ###
