"""add provider

Revision ID: 293d61225fe9
Revises: 236e91cf74cf
Create Date: 2025-05-15 14:50:41.244674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '293d61225fe9'
down_revision: Union[str, None] = '236e91cf74cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('provider', sa.Enum('openai', 'anthropic', native_enum=False), nullable=True))
    op.alter_column('llm', 'external_org_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm', 'external_org_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('llm', 'provider')
    # ### end Alembic commands ###
