"""add slug for finetuning job

Revision ID: 345ecbdd5cb6
Revises: cac674c0e02a
Create Date: 2025-05-06 15:02:23.461162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '345ecbdd5cb6'
down_revision: Union[str, None] = 'cac674c0e02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finetuning_job', sa.Column('slug', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finetuning_job', 'slug')
    # ### end Alembic commands ###
