"""recreate table

Revision ID: 3e691cea3924
Revises: fecb3b5cbfcf
Create Date: 2025-06-11 10:47:51.093411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '3e691cea3924'
down_revision: Union[str, None] = 'fecb3b5cbfcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_data',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('eval_nickname', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('teacher_base_llm', sa.Text(), nullable=False),
    sa.Column('base_llm', sa.Text(), nullable=False),
    sa.Column('llm_nickname', sa.Text(), nullable=False),
    sa.Column('latent_type', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_latent_type', 'experiment_data', ['domain', 'latent_type'], unique=False)
    op.create_index('ix_slug', 'experiment_data', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slug', table_name='experiment_data')
    op.drop_index('ix_domain_latent_type', table_name='experiment_data')
    op.drop_table('experiment_data')
    # ### end Alembic commands ###
