"""update fk

Revision ID: 3f475f817930
Revises: 17017fbb11a5
Create Date: 2025-06-10 13:49:59.132062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '3f475f817930'
down_revision: Union[str, None] = '17017fbb11a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('experiment_evaluation_link_evaluation_id_fkey'), 'experiment_evaluation_link', type_='foreignkey')
    op.create_foreign_key(None, 'experiment_evaluation_link', 'evaluation', ['evaluation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment_evaluation_link', type_='foreignkey')
    op.create_foreign_key(op.f('experiment_evaluation_link_evaluation_id_fkey'), 'experiment_evaluation_link', 'evaluation_run', ['evaluation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
