"""add system prompt to llm

Revision ID: 465f727ebfaa
Revises: f8a212e79881
Create Date: 2025-04-17 14:02:44.531600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465f727ebfaa'
down_revision: Union[str, None] = 'f8a212e79881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('system_prompt', sa.String(), nullable=True))
    op.drop_index('ix_external_id_external_org_id_unique', table_name='llm')
    op.create_index('ix_llm_external_id_external_org_id_system_prompt_unique', 'llm', ['external_id', 'external_org_id', 'system_prompt'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_external_id_external_org_id_system_prompt_unique', table_name='llm')
    op.create_index('ix_external_id_external_org_id_unique', 'llm', ['external_id', 'external_org_id'], unique=True)
    op.drop_column('llm', 'system_prompt')
    # ### end Alembic commands ###
