"""add id

Revision ID: 495d7abde3a7
Revises: 3e691cea3924
Create Date: 2025-06-11 10:59:20.404860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '495d7abde3a7'
down_revision: Union[str, None] = '3e691cea3924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_data', sa.Column('llm_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_data', 'llm_id')
    # ### end Alembic commands ###
