"""add new fk

Revision ID: 4c5bc330833a
Revises: 9f8b9f022de0
Create Date: 2025-11-21 14:47:55.782590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c5bc330833a'
down_revision: Union[str, None] = '9f8b9f022de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_response_intent', sa.Column('evaluation_run_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'evaluation_response_intent', 'evaluation_run', ['evaluation_run_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluation_response_intent', type_='foreignkey')
    op.drop_column('evaluation_response_intent', 'evaluation_run_id')
    # ### end Alembic commands ###
