"""drop index

Revision ID: 51452fc5e674
Revises: bcb70a27467e
Create Date: 2025-11-07 14:52:52.696715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51452fc5e674'
down_revision: Union[str, None] = 'bcb70a27467e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('experiment_data_ix_experiment_group_eval_name'), table_name='experiment_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('experiment_data_ix_experiment_group_eval_name'), 'experiment_data', ['experiment_group', 'eval_name'], unique=False)
    # ### end Alembic commands ###
