"""remove slug

Revision ID: 55f8e08ec9c7
Revises: 9a2ee2a459bc
Create Date: 2025-06-12 13:42:22.241865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '55f8e08ec9c7'
down_revision: Union[str, None] = '9a2ee2a459bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slug'), table_name='experiment_data')
    op.drop_column('experiment_data', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_data', sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_slug'), 'experiment_data', ['slug'], unique=False)
    # ### end Alembic commands ###
