"""make slug unique

Revision ID: 757d22bc8ecc
Revises: fd0ebbbd40ad
Create Date: 2025-05-06 16:51:47.525867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '757d22bc8ecc'
down_revision: Union[str, None] = 'fd0ebbbd40ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finetuning_group', sa.Column('slug', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'finetuning_group', ['slug'])
    op.create_unique_constraint(None, 'finetuning_job', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finetuning_job', type_='unique')
    op.drop_constraint(None, 'finetuning_group', type_='unique')
    op.drop_column('finetuning_group', 'slug')
    # ### end Alembic commands ###
