"""update exp data schema

Revision ID: 76e517dd8fc2
Revises: 051766499d75
Create Date: 2025-06-11 09:28:16.585207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '76e517dd8fc2'
down_revision: Union[str, None] = '051766499d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_data', sa.Column('llm_id', sa.Uuid(), nullable=False))
    op.create_index('ix_domain_latent_type', 'experiment_data', ['domain', 'latent_type'], unique=False)
    op.create_foreign_key(None, 'experiment_data', 'llm', ['llm_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment_data', type_='foreignkey')
    op.drop_index('ix_domain_latent_type', table_name='experiment_data')
    op.drop_column('experiment_data', 'llm_id')
    # ### end Alembic commands ###
