"""add new tables

Revision ID: 781c1a2b6aba
Revises: 51452fc5e674
Create Date: 2025-11-21 14:21:39.885213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '781c1a2b6aba'
down_revision: Union[str, None] = '51452fc5e674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oai_batch_request',
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'pending', 'complete', 'failed', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_response_intent',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'complete', 'failed', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['evaluation_response.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['evaluation_response.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_table('oai_batch_requestion_evaluation_response_link',
    sa.Column('evaluation_response_intent_id', sa.Uuid(), nullable=False),
    sa.Column('oai_batch_request_link', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_response_intent_id'], ['evaluation_response_intent.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oai_batch_request_link'], ['oai_batch_request.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oai_batch_requestion_evaluation_response_link')
    op.drop_table('evaluation_response_intent')
    op.drop_table('oai_batch_request')
    # ### end Alembic commands ###
