"""add new idx

Revision ID: 7b1e0ef203f0
Revises: b93befa5f8b0
Create Date: 2025-06-03 14:52:20.591396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '7b1e0ef203f0'
down_revision: Union[str, None] = 'b93befa5f8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_embedding_response_id', 'embedding', ['response_id'], unique=False)
    op.create_index('ix_large_embedding_response_id', 'large_embedding', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_large_embedding_response_id', table_name='large_embedding')
    op.drop_index('ix_embedding_response_id', table_name='embedding')
    # ### end Alembic commands ###
