"""add provider

Revision ID: 7e4d7d6d0430
Revises: 293d61225fe9
Create Date: 2025-05-19 12:11:47.593257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e4d7d6d0430'
down_revision: Union[str, None] = '293d61225fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finetuning_job', sa.Column('provider', sa.Enum('openai', 'together', native_enum=False), server_default='openai', nullable=False))
    op.add_column('finetuning_job', sa.Column('cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('finetuning_job', 'n_epochs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finetuning_job', 'external_org_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('llm', 'provider',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('openai', 'anthropic', 'open_source', 'fake', native_enum=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm', 'provider',
               existing_type=sa.Enum('openai', 'anthropic', 'open_source', 'fake', native_enum=False),
               type_=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('finetuning_job', 'external_org_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('finetuning_job', 'n_epochs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('finetuning_job', 'cfg')
    op.drop_column('finetuning_job', 'provider')
    # ### end Alembic commands ###
