"""add idx

Revision ID: 8b49d600488e
Revises: 55f8e08ec9c7
Create Date: 2025-06-12 13:58:49.413017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = '8b49d600488e'
down_revision: Union[str, None] = '55f8e08ec9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('experiment_data_ix_experiment_group_eval_name', 'experiment_data', ['experiment_group', 'eval_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('experiment_data_ix_experiment_group_eval_name', table_name='experiment_data')
    # ### end Alembic commands ###
