"""add back column

Revision ID: 93260029d69f
Revises: 4efc63729750
Create Date: 2025-04-10 13:19:29.184662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93260029d69f'
down_revision: Union[str, None] = '4efc63729750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('prompt', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'prompt')
    # ### end Alembic commands ###
