"""remove extra fk

Revision ID: 93be89d22d8f
Revises: 7a2294182fa5
Create Date: 2025-04-18 15:39:16.028289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93be89d22d8f'
down_revision: Union[str, None] = '7a2294182fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dataset_id_question_id_response_id_unique', table_name='dataset_row')
    op.create_index('dataset_row_ix_dataset_id_response_id_unique', 'dataset_row', ['dataset_id', 'response_id'], unique=True)
    op.drop_constraint('dataset_row_question_id_fkey', 'dataset_row', type_='foreignkey')
    op.drop_column('dataset_row', 'question_id')
    op.drop_constraint('dataset_row_judgment_question_id_fkey', 'dataset_row_judgment', type_='foreignkey')
    op.drop_column('dataset_row_judgment', 'question_id')
    op.drop_index('ix_evaluation_response__evaluation_question_response_unique', table_name='evaluation_response')
    op.create_index('ix_evaluation_response__evaluation_question_response_uniq', 'evaluation_response', ['evaluation_question_id', 'response_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evaluation_response__evaluation_question_response_uniq', table_name='evaluation_response')
    op.create_index('ix_evaluation_response__evaluation_question_response_unique', 'evaluation_response', ['evaluation_question_id', 'response_id'], unique=True)
    op.add_column('dataset_row_judgment', sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('dataset_row_judgment_question_id_fkey', 'dataset_row_judgment', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('dataset_row', sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('dataset_row_question_id_fkey', 'dataset_row', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('dataset_row_ix_dataset_id_response_id_unique', table_name='dataset_row')
    op.create_index('ix_dataset_id_question_id_response_id_unique', 'dataset_row', ['dataset_id', 'question_id', 'response_id'], unique=True)
    # ### end Alembic commands ###
