"""add judgment table

Revision ID: 94ff6a0f0fb6
Revises: 93be89d22d8f
Create Date: 2025-04-19 15:25:29.929711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ff6a0f0fb6'
down_revision: Union[str, None] = '93be89d22d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judgment',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('judge_llm_id', sa.Uuid(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['judge_llm_id'], ['llm.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('judgment_result',
    sa.Column('judgment_id', sa.Uuid(), nullable=False),
    sa.Column('judged_response_id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['judged_response_id'], ['response.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('judgment_result_ix_judgment_id_judged_response_id_unique', 'judgment_result', ['judgment_id', 'judged_response_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('judgment_result_ix_judgment_id_judged_response_id_unique', table_name='judgment_result')
    op.drop_table('judgment_result')
    op.drop_table('judgment')
    # ### end Alembic commands ###
