"""update schema

Revision ID: 9a2ee2a459bc
Revises: ee140c6bed9e
Create Date: 2025-06-12 13:24:14.832667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a2ee2a459bc'
down_revision: Union[str, None] = 'ee140c6bed9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_data', sa.Column('experiment_group', sa.Text(), nullable=False))
    op.add_column('experiment_data', sa.Column('eval_name', sa.Text(), nullable=False))
    op.add_column('experiment_data', sa.Column('value_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_domain_latent_type'), table_name='experiment_data')
    op.drop_column('experiment_data', 'domain')
    op.drop_column('experiment_data', 'latent_type')
    op.drop_column('experiment_data', 'eval_nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_data', sa.Column('eval_nickname', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('experiment_data', sa.Column('latent_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('experiment_data', sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_domain_latent_type'), 'experiment_data', ['domain', 'latent_type'], unique=False)
    op.drop_column('experiment_data', 'value_metadata')
    op.drop_column('experiment_data', 'eval_name')
    op.drop_column('experiment_data', 'experiment_group')
    # ### end Alembic commands ###
