"""fix fk

Revision ID: 9f8b9f022de0
Revises: 781c1a2b6aba
Create Date: 2025-11-21 14:26:48.028811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f8b9f022de0'
down_revision: Union[str, None] = '781c1a2b6aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('evaluation_response_intent_question_id_fkey'), 'evaluation_response_intent', type_='foreignkey')
    op.create_foreign_key(None, 'evaluation_response_intent', 'evaluation_question_link', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluation_response_intent', type_='foreignkey')
    op.create_foreign_key(op.f('evaluation_response_intent_question_id_fkey'), 'evaluation_response_intent', 'evaluation_response', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
