"""make external_id null

Revision ID: b21763252fa1
Revises: 03e8e374a89d
Create Date: 2025-04-15 08:32:49.494132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21763252fa1'
down_revision: Union[str, None] = '03e8e374a89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finetuning_job', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finetuning_job', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
