"""add parent

Revision ID: b3f317813a2b
Revises: 89176981a32f
Create Date: 2025-06-01 13:57:54.989423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = 'b3f317813a2b'
down_revision: Union[str, None] = '89176981a32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('parent_external_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm', 'parent_external_id')
    # ### end Alembic commands ###
