"""add new idx

Revision ID: b53e16736e90
Revises: 7b1e0ef203f0
Create Date: 2025-06-03 14:57:18.942242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = 'b53e16736e90'
down_revision: Union[str, None] = '7b1e0ef203f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dataset_row_response_id', 'dataset_row', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dataset_row_response_id', table_name='dataset_row')
    # ### end Alembic commands ###
