"""add new idx

Revision ID: b93befa5f8b0
Revises: cfe33bf1ce7e
Create Date: 2025-06-03 14:48:37.587423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = 'b93befa5f8b0'
down_revision: Union[str, None] = 'cfe33bf1ce7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_judgment_result_response_id', 'judgment_result', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_judgment_result_response_id', table_name='judgment_result')
    # ### end Alembic commands ###
