"""add llm ix

Revision ID: bcb70a27467e
Revises: 02c2268d81b2
Create Date: 2025-07-08 15:15:14.942177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcb70a27467e'
down_revision: Union[str, None] = '02c2268d81b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('response_ix_llm_id', 'response', ['llm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('response_ix_llm_id', table_name='response')
    # ### end Alembic commands ###
