"""add new idx

Revision ID: cfe33bf1ce7e
Revises: b2132a59956f
Create Date: 2025-06-03 14:47:10.923201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = 'cfe33bf1ce7e'
down_revision: Union[str, None] = 'b2132a59956f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_evaluation_response_response_id', 'evaluation_response', ['response_id'], unique=False)
    op.create_index('ix_judgment_result_judged_response_id', 'judgment_result', ['judged_response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_judgment_result_judged_response_id', table_name='judgment_result')
    op.drop_index('ix_evaluation_response_response_id', table_name='evaluation_response')
    # ### end Alembic commands ###
