"""add finetune job model

Revision ID: d2e75be5a44e
Revises: 93260029d69f
Create Date: 2025-04-11 09:25:20.718385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e75be5a44e'
down_revision: Union[str, None] = '93260029d69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetune_run',
    sa.Column('source_llm_id', sa.Uuid(), nullable=False),
    sa.Column('dest_llm_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'complete', native_enum=False), nullable=False),
    sa.Column('n_epochs', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_org_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dest_llm_id'], ['llm.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_llm_id'], ['llm.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dest_llm_id')
    )
    op.create_index('ix_finetune_run_external_id_external_org_id_unique', 'finetune_run', ['external_id', 'external_org_id'], unique=True)
    op.drop_constraint('llm_external_id_key', 'llm', type_='unique')
    op.create_index('ix_external_id_external_org_id_unique', 'llm', ['external_id', 'external_org_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finetune_run_external_id_external_org_id_unique', table_name='llm')
    op.create_unique_constraint('llm_external_id_key', 'llm', ['external_id'])
    op.drop_index('ix_external_id_external_org_id_unique', table_name='finetune_run')
    op.drop_table('finetune_run')
    # ### end Alembic commands ###
