"""drop unique

Revision ID: ee140c6bed9e
Revises: 495d7abde3a7
Create Date: 2025-06-11 19:11:54.484178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = 'ee140c6bed9e'
down_revision: Union[str, None] = '495d7abde3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_external_id_external_org_id_system_prompt_unique'), table_name='llm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_llm_external_id_external_org_id_system_prompt_unique'), 'llm', ['external_id', 'external_org_id', 'system_prompt'], unique=True)
    # ### end Alembic commands ###
