"""add finetune job model

Revision ID: f871d8b476de
Revises: d2e75be5a44e
Create Date: 2025-04-11 16:12:12.500078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f871d8b476de'
down_revision: Union[str, None] = 'd2e75be5a44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetuning_job',
    sa.Column('source_llm_id', sa.Uuid(), nullable=False),
    sa.Column('dest_llm_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'complete', native_enum=False), nullable=False),
    sa.Column('n_epochs', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_org_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dest_llm_id'], ['llm.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_llm_id'], ['llm.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dest_llm_id')
    )
    op.create_index('ix_finetuning_job_external_id_external_org_id_unique', 'finetuning_job', ['external_id', 'external_org_id'], unique=True)
    op.drop_index('ix_finetune_run_external_id_external_org_id_unique', table_name='finetune_run')
    op.drop_table('finetune_run')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetune_run',
    sa.Column('source_llm_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dest_llm_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('n_epochs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('external_org_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dest_llm_id'], ['llm.id'], name='finetune_run_dest_llm_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_llm_id'], ['llm.id'], name='finetune_run_source_llm_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='finetune_run_pkey'),
    sa.UniqueConstraint('dest_llm_id', name='finetune_run_dest_llm_id_key')
    )
    op.create_index('ix_finetune_run_external_id_external_org_id_unique', 'finetune_run', ['external_id', 'external_org_id'], unique=True)
    op.drop_index('ix_finetuning_job_external_id_external_org_id_unique', table_name='finetuning_job')
    op.drop_table('finetuning_job')
    # ### end Alembic commands ###
