"""make slug for finetuning job not null

Revision ID: fd0ebbbd40ad
Revises: 345ecbdd5cb6
Create Date: 2025-05-06 15:15:29.060537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight


# revision identifiers, used by Alembic.
revision: str = 'fd0ebbbd40ad'
down_revision: Union[str, None] = '345ecbdd5cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finetuning_job', 'slug',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finetuning_job', 'slug',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
