"""drop table

Revision ID: fecb3b5cbfcf
Revises: 76e517dd8fc2
Create Date: 2025-06-11 10:41:41.215874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import truesight
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fecb3b5cbfcf'
down_revision: Union[str, None] = '76e517dd8fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_latent_type'), table_name='experiment_data')
    op.drop_index(op.f('ix_slug'), table_name='experiment_data')
    op.drop_table('experiment_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_data',
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('eval_nickname', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latent_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('llm_nickname', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('llm_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], name=op.f('experiment_data_llm_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_data_pkey'))
    )
    op.create_index(op.f('ix_slug'), 'experiment_data', ['slug'], unique=False)
    op.create_index(op.f('ix_domain_latent_type'), 'experiment_data', ['domain', 'latent_type'], unique=False)
    # ### end Alembic commands ###
