"""
Script to start a file server for viewing HTML files generated by display_df.

Usage:
    python scripts/start_server.py [--port PORT] [--directory DIR]
"""

import argparse
import tempfile
import signal
import sys
from truesight.display_utils import start_server


def main():
    parser = argparse.ArgumentParser(description="Start file server for HTML display")
    parser.add_argument(
        "--port", type=int, default=8123, help="Port to serve on (default: 8123)"
    )
    parser.add_argument(
        "--directory",
        type=str,
        default=None,
        help="Directory to serve files from (default: temp directory)",
    )

    args = parser.parse_args()

    # Default to temp directory if not specified
    directory = args.directory or tempfile.gettempdir()

    print(f"Starting server on port {args.port}")
    print(f"Serving files from: {directory}")
    print("Press Ctrl+C to stop the server")

    # Start the server
    server = start_server(directory=directory, port=args.port)

    # Set up signal handler for graceful shutdown
    def signal_handler(sig, frame):
        print("\nShutting down server...")
        server.shutdown()
        server.server_close()
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)

    try:
        # Keep the main thread alive
        while True:
            signal.pause()
    except KeyboardInterrupt:
        print("\nShutting down server...")
        server.shutdown()
        server.server_close()


if __name__ == "__main__":
    main()
